#!/usr/bin/env fish
set -l JENKINS_URL https://jenkins.initios.es
set -l JENKINS_CRUMB (curl --netrc --silent "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)")
curl --netrc --silent -X POST -H $JENKINS_CRUMB -F "jenkinsfile=<Jenkinsfile" $JENKINS_URL/pipeline-model-converter/validate

